version: '2.4'

services:

  xana-app:
    container_name: xana-app
    restart: always
    image: xana-app
    #build: .
    command: bash -c "service cron start && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:80 "
    network_mode: "host"
    ports:
      - "80:80"
    depends_on:
      - xana-db
    volumes:
      - .:/home/xana_v2

  xana-db:
    container_name: xana-db
    restart: always
    image: postgres
    network_mode: "host"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - TZ=Africa/Djibouti
      - POSTGRES_DB=xana_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespwd
    ports:
      - "5433:5432"