# Generated by Django 3.2.6 on 2022-02-04 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('params', models.CharField(max_length=255)),
                ('values', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('process', models.IntegerField()),
                ('message_description', models.CharField(max_length=255)),
                ('etat', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PackageData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_package_date', models.IntegerField()),
                ('balance_data', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField()),
                ('frais', models.IntegerField()),
                ('promotion1', models.CharField(max_length=255)),
                ('promotion1_data', models.CharField(max_length=255)),
                ('promotion2', models.CharField(max_length=255)),
                ('promotion2_data', models.CharField(max_length=255)),
                ('promotion3', models.CharField(max_length=255)),
                ('promotion3_data', models.CharField(max_length=255)),
                ('promotion4', models.CharField(max_length=255)),
                ('promotion4_data', models.CharField(max_length=255)),
                ('promotion5', models.CharField(max_length=255)),
                ('promotion5_data', models.CharField(max_length=255)),
                ('quantite_data', models.CharField(max_length=255)),
                ('updated_date', models.DateTimeField()),
                ('validite', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('balance_voix', models.CharField(max_length=255)),
                ('quantite_voix', models.CharField(max_length=255)),
                ('types', models.IntegerField()),
                ('fraisrg', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_queue', models.IntegerField()),
                ('action_type', models.IntegerField()),
                ('command_content', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField()),
                ('status', models.IntegerField()),
                ('updated_date', models.DateTimeField()),
                ('msisdn', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=255)),
                ('error_code', models.IntegerField()),
                ('error_description', models.CharField(max_length=255)),
                ('etat', models.CharField(max_length=255)),
                ('thread_name', models.CharField(max_length=255)),
                ('thread_number', models.IntegerField()),
                ('fee', models.DecimalField(decimal_places=10, max_digits=25)),
                ('ip_adresse_client', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='QueueHist',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_queue_hist', models.IntegerField()),
                ('action_type', models.IntegerField()),
                ('command_content', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField()),
                ('status', models.IntegerField()),
                ('updated_date', models.DateTimeField()),
                ('error_description', models.CharField(max_length=255)),
                ('msisdn', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=255)),
                ('error_code', models.IntegerField()),
                ('etat', models.CharField(max_length=255)),
                ('thread_name', models.CharField(max_length=255)),
                ('thread_number', models.IntegerField()),
                ('fee', models.DecimalField(decimal_places=10, max_digits=25)),
                ('ip_adresse_client', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AlertQueueHist',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('check_1', models.BooleanField(default=False)),
                ('check_2', models.BooleanField(default=False)),
                ('check_3', models.BooleanField(default=False)),
                ('reported', models.BooleanField(default=False)),
                ('corrected', models.BooleanField(default=False)),
                ('id_queue_hist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.queuehist')),
            ],
        ),
        migrations.CreateModel(
            name='AlertQueue',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('check_1', models.BooleanField(default=False)),
                ('check_2', models.BooleanField(default=False)),
                ('check_3', models.BooleanField(default=False)),
                ('reported', models.BooleanField(default=False)),
                ('corrected', models.BooleanField(default=False)),
                ('id_queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.queue')),
            ],
        ),
    ]
