# Generated by Django 3.2.6 on 2022-02-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagedata',
            name='balance_voix',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='packagedata',
            name='promotion1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='packagedata',
            name='promotion1_data',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='packagedata',
            name='promotion2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='packagedata',
            name='promotion2_data',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='packagedata',
            name='promotion3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='packagedata',
            name='promotion3_data',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='packagedata',
            name='promotion4',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='packagedata',
            name='promotion4_data',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='packagedata',
            name='promotion5',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='packagedata',
            name='promotion5_data',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
