# Generated by Django 3.2.6 on 2022-02-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220222_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagedata',
            name='promotion1',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
