# Generated by Django 3.2.6 on 2022-02-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_packagedata_promotion1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagedata',
            name='balance_voix',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='packagedata',
            name='promotion1_data',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='packagedata',
            name='promotion2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='packagedata',
            name='promotion2_data',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='packagedata',
            name='promotion3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='packagedata',
            name='promotion3_data',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='packagedata',
            name='promotion4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='packagedata',
            name='promotion4_data',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='packagedata',
            name='promotion5',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='packagedata',
            name='promotion5_data',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
