# Generated by Django 3.2.6 on 2022-02-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220222_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagedata',
            name='quantite_voix',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
