# Generated by Django 3.2.6 on 2022-02-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20220222_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='thread_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='queuehist',
            name='thread_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
