# Generated by Django 3.2.6 on 2022-02-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20220222_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='command_content',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='queuehist',
            name='command_content',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
