# Generated by Django 3.2.6 on 2022-02-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20220222_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='action_type',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='queue',
            name='error_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='queue',
            name='etat',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='queue',
            name='fee',
            field=models.DecimalField(decimal_places=10, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='queue',
            name='msisdn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='queue',
            name='pincode',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='queue',
            name='status',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='queue',
            name='thread_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='queuehist',
            name='action_type',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='queuehist',
            name='error_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='queuehist',
            name='etat',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='queuehist',
            name='fee',
            field=models.DecimalField(decimal_places=10, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='queuehist',
            name='msisdn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='queuehist',
            name='pincode',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='queuehist',
            name='status',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='queuehist',
            name='thread_number',
            field=models.IntegerField(null=True),
        ),
    ]
