# Generated by Django 3.2.6 on 2022-04-27 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20220222_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilePPBU',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField()),
                ('folder', models.CharField(max_length=255)),
                ('loaded', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='queue',
            name='msisdn',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='DataPPBU',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=255)),
                ('date_recharge', models.DateTimeField()),
                ('profil_ocs', models.CharField(max_length=255)),
                ('data', models.CharField(max_length=4000)),
                ('id_fileppbu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fileppbu')),
            ],
        ),
    ]
