# Generated by Django 3.2.6 on 2022-04-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20220427_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='msisdn',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
